"""Antenna Helicoid array in traditional model training .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vf8yjz3Xh9RqsL8wJZlh9i7Z6UFemhnG

Reference data/ Link:

*    Introdction to QFT: https://pennylane.ai/qml/demos/tutorial_qft/
*    QFT application : https://pennylane.ai/qml/demos/tutorial_expressivity_fourier_series/
*   Wiki reference: https://en.wikipedia.org/wiki/Quantum_phase_estimation_algorithm

* Quantum long short terms demo code: https://github.com/Abeeekoala/Quantum-Train-LSTM-PennyLane-Demo/blob/master/QTLSTM_pennylane.ipynb

* Quantum embedded : https://pennylane.ai/qml/glossary/quantum_embedding/

* Quantum Classical machine learning: hybrid quantum-classical machine learning
"""

!nvcc -V
#!pip install cudnn=7.6.5=cuda10.1_0
#!pip install cudnn

!pip uninstall tensorflow
#!pip install tensorflow[and-cuda]
!pip install tensorflow==2.15.0
#!pip install tensorflow
!pip install --upgrade pip
#!pip install --ignore-installed --upgrade

#tradition ML approach

# Commented out IPython magic to ensure Python compatibility.
#-----------------------Regression model----------------
# %load_ext tensorboard
# Import useful library
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorboard
from datetime import datetime
from packaging import version
from tensorflow import keras
!rm -rf ./logs/
print(tf.__version__)
print(tf.config.list_physical_devices())

print(tf.sysconfig.get_build_info()['cuda_version'])

print(tf.sysconfig.get_build_info()['cudnn_version'])

!python -V

!nvcc --version

#!pip install --upgrade nvidia-pyindex
!nvidia-smi

import os
os.environ["TF_CPP_MAX_VLOG_LEVEL"] = "1"
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

#tf.debugging.set_log_device_placement(True)
#tf.config.list_physical_devices('GPU')
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))#/job:localhost/replica:0/task:0/device:GPU:0
#tf.debugging.set_log_device_placement(False)

# Import data as CSV (Remember to normalized your data )
# data = pd.read_csv("Helical_phase_databaseV4_MC.csv")
data = pd.read_csv("Helical_phase_databaseV6_MC_Clockwise.csv")
data

#data normalization
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

ct = make_column_transformer((MinMaxScaler(),["Phi" ,"Theta"]))#["Element" + str(x+1)  for x in range(64)])


#Create X and Y
Y = data.drop(["Phi","Theta"],axis=1)
X = data.get(["Phi","Theta"])

#Built a training and testing sets
X_train, X_test, Y_train,Y_test = train_test_split(X, Y,test_size = 0.2, random_state=25)
# X_train

#Fit the column transformer to our training data
ct.fit(X_train)

#Transform training and test data with normalization
X_train_normal = ct.transform(X_train)
X_test_normal = ct.transform(X_test)

X_train_normal

Y_train

#Reshape for LSTM
X_train_normal = X_train_normal.reshape((X_train_normal.shape[0], 1, X_train_normal.shape[1]))
X_test_normal = X_test_normal.reshape((X_test_normal.shape[0], 1, X_test_normal.shape[1]))

X_train_normal
#Reshape for LSTM
X_train_normal = X_train_normal.reshape(len(X_train_normal), 2, 1)
X_test_normal = X_test_normal.reshape(len(X_test_normal),2,1)

X_train_normal.shape


# Neural network model

#1. Create the model
tf.random.set_seed(42)
model = tf.keras.Sequential([
    tf.keras.layers.Input((2,),name="input_llayer"),
    tf.keras.layers.Dense(900,activation="relu"),
    tf.keras.layers.Dense(500,activation="relu"),
    tf.keras.layers.Dense(300,activation="relu"),
    tf.keras.layers.Dense(100,activation="relu"),
    tf.keras.layers.Dense(64)
])

#1.5 customise losses function

def custom_loss(y_true, y_pred):

  # Calculate loss
  DTR = tf.constant((np.pi/180.))
  #loss = (tf.reduce_sum(((tf.math.cos(y_pred*DTR)-tf.math.cos(y_true*DTR))**2))/8) +(tf.reduce_sum(((tf.math.sin(y_pred*DTR)-tf.math.sin(y_true*DTR))**2))/8)
  #loss =  ((((tf.math.cos(y_pred)-tf.math.cos(y_true)))**2) +(((tf.math.sin(y_pred)-tf.math.sin(y_true)))**2))*tf.math.cos(y_true-y_pred)**2#<-- this is in radian
  loss = (((tf.math.cos(y_pred)-tf.math.cos(y_true)))**2) +(((tf.math.sin(y_pred)-tf.math.sin(y_true)))**2)
  #loss = tf.math.cos((y_true-y_pred)**2)
  return  tf.reduce_mean(loss) # tf.keras.losses.mae #loss

#2.Compile the model
model.compile(loss = custom_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              metrics= custom_loss)#


#2.5 . log the model
logdir="logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

#3. Fit the model
history=model.fit(X_train_normal,Y_train,validation_split=0.2, epochs =150,callbacks=[tensorboard_callback])

pd.DataFrame(history.history).plot()
plt.ylabel("loss")
plt.xlabel("epochs")

#3.5 Change learning rate and fit again
model.compile(loss =custom_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
              metrics= [custom_loss])#
history1=model.fit(X_train_normal,Y_train,validation_split=0.2, epochs =100,callbacks=[tensorboard_callback])

pd.DataFrame(history1.history).plot()
plt.ylabel("loss")
plt.xlabel("epochs")

#3.5 Change learning rate and fit again
model.compile(loss =custom_loss,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.00001),
              metrics= [custom_loss])#
history2=model.fit(X_train_normal,Y_train,validation_split=0.2, epochs = 160,callbacks=[tensorboard_callback])

model.summary()

param_size = 0
buffer_size = 0
tf.size(model)

pd.DataFrame(history2.history).plot()
plt.ylabel("loss")
plt.xlabel("epochs")

from keras import backend as K
K.set_value(model.optimizer.learning_rate,0.00001)

history = model.fit(X_train_normal,Y_train,initial_epoch=120, epochs = 220,callbacks=[tensorboard_callback])

#4 answer output
phi = 261/360
theta = (90-80)/20 #(90-81)/(95-81)#theta = (90-75)/(115-75)
compare = data.iloc[3500,2:-2]
model.predict([[phi ,theta]]) #- compare.values

model.predict(np.array([[190/360, (90-80)/(100-80)]]))

data.iloc[3500,0:-2]

#Test the model

def DeepLearningArrayFactor(phi,SPhi,STheta):
    """Generate a truncated Fourier series, where the data gets re-scaled."""
    STheta = STheta-81;
    Thetaa = 90*DTR;
    Eview = 0
    phase_input=np.mod(model.predict([[SPhi ,STheta]]),360)
    UNu = 8
    for M in range(UNu):
        phase_exp = np.complex128(phase_input[0,M]*DTR)#np.complex128(-1j*k*(M-(UNu/2))*dx*np.sin(Theta0)*np.cos(phi0*DTR))
        exponent = np.complex128(1j*k*(M-(UNu/2))*dx*np.sin(Thetaa)*np.cos(phi))
        Eview += np.exp(exponent+phase_exp)
    # res = (Eview*np.conjugate(Eview))/(UNu*UNu)
    res = (Eview)/(UNu)
    return np.real(res)

target_y[360,360]

# ArrayFactor(phi,phi0)
SPhi=261
Theta = 90
target_y = np.array([DeepLearningArrayFactor(phi_,SPhi,Theta) for phi_ in phi], requires_grad=False)
# target_y
plt.plot(phi, target_y, c='black')
plt.scatter(phi, target_y, facecolor='white', edgecolor='black')
plt.ylim(-1, 1)
plt.xlim(-0, 7)
plt.show();

with tf.keras.utils.custom_object_scope({'custom_loss':custom_loss}):
    custom_loss =custom_loss

#5- save model
# model.save("/content/drive/MyDrive/TestModel_V2Mk2")
#tf.saved_model.save(model,"/content/TestHelicoidModel_V1Mk1")
#model.save('/content/TestHelicoidModel_V1Mk4_MC_SupersmallSizemodel.h5')
# model.save('/content/testing.h5')
model.save("/content/helicoidDNNmodel.keras")
# model.export("/content/TestHelicoidModel_V1Mk1")

#5b- save model in TFlite
from tensorflow import lite
converter = lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open('Test8x8HelicoidModel_V1Mk6_MC_clockwise.tflite', 'wb').write(tflite_model)

def custom_loss(y_true, y_pred):

   # Calculate loss
   DTR = tf.constant((np.pi/180.))
   #loss = (tf.reduce_sum(((tf.math.cos(y_pred*DTR)-tf.math.cos(y_true*DTR))**2))/8) +(tf.reduce_sum(((tf.math.sin(y_pred*DTR)-tf.math.sin(y_true*DTR))**2))/8)
   #loss =  ((((tf.math.cos(y_pred)-tf.math.cos(y_true)))**2) +(((tf.math.sin(y_pred)-tf.math.sin(y_true)))**2))*tf.math.cos(y_true-y_pred)**2#<-- this is in radian
   loss = (((tf.math.cos(y_pred)-tf.math.cos(y_true)))**2) +(((tf.math.sin(y_pred)-tf.math.sin(y_true)))**2)
   #loss = tf.math.cos((y_true-y_pred)**2)
   return  tf.reduce_mean(loss) # tf.keras.losses.mae #loss

NewModel = tf.keras.models.load_model('testing.h5', custom_objects={'custom_loss': custom_loss})

